//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public string To { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public Nullable<long> InvoiceID { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
