//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> Quantity { get; set; }
        public string Price { get; set; }
        public Nullable<long> InvoiceID { get; set; }
        public Nullable<long> OrderID { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Products1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
